CREATE DATABASE JFXPDV;

USE JFXPDV;

CREATE TABLE USUARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	NIVEL_DE_ACESSO ENUM('ADMINISTRADOR', 'GERENTE', 'CAIXA') NOT NULL
);

CREATE TABLE CLIENTES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100),
  RG VARCHAR (30),
  CPF VARCHAR (20),
  TELEFONE VARCHAR(30),
  CELULAR VARCHAR(30),
  EMAIL VARCHAR(200),
  BAIRRO VARCHAR (100),
  RUA VARCHAR (255), /* ENDERECO */
  NUMERO INT,
  COMPLEMENTO VARCHAR (200),
  CEP VARCHAR(100),
  CIDADE VARCHAR (100),
  ESTADO VARCHAR (2)
);