CREATE DATABASE JFXPDV;

USE JFXPDV;

CREATE TABLE USUARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	NIVEL_DE_ACESSO ENUM('ADMINISTRADOR', 'CAIXA') NOT NULL
);

CREATE TABLE CLIENTES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO ENUM('PF', 'PJ'),
	NOME VARCHAR(100) NOT NULL,
    CPF_CNPJ CHAR (18) NOT NULL,
	RG CHAR(13),
	TELEFONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100),
    ESTADO VARCHAR (2) NOT NULL,
    CIDADE VARCHAR (100) NOT NULL,
    RUA VARCHAR (255) NOT NULL,
	BAIRRO VARCHAR (100) NOT NULL,
    CEP CHAR(9) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR (200)
);

