INSERT INTO USUARIOS(NOME, LOGIN, SENHA, NIVEL_DE_ACESSO) VALUES('Administrador', 'admin', 'admin', 'ADMINISTRADOR');
INSERT INTO USUARIOS(NOME, LOGIN, SENHA, NIVEL_DE_ACESSO) VALUES('Gerente', 'gerente', 'gerente', 'GERENTE');
INSERT INTO USUARIOS(NOME, LOGIN, SENHA, NIVEL_DE_ACESSO) VALUES('Caixa', 'caixa', 'caixa', 'CAIXA');
