CREATE DATABASE TESTE_PDV;

USE TESTE_PDV;

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	NIVEL_DE_ACESSO ENUM('ADMINISTRADOR', 'GERENTE', 'CAIXA') NOT NULL
);

INSERT INTO USUARIOS(NOME, LOGIN, SENHA, NIVEL_DE_ACESSO) VALUES('Administrador', 'admin', 'admin', 'ADMINISTRADOR');
INSERT INTO USUARIOS(NOME, LOGIN, SENHA, NIVEL_DE_ACESSO) VALUES('Gerente', 'gerente', 'gerente', 'GERENTE');
INSERT INTO USUARIOS(NOME, LOGIN, SENHA, NIVEL_DE_ACESSO) VALUES('Caixa', 'caixa', 'caixa', 'CAIXA');

SELECT * FROM USUARIOS;